
spring:
  datasource:
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    call-setters-on-nulls: false
server:
  port: 8080
  tomcat:
    max-threads: 200