spring:
  application:
    name: springboot 2.0 集成mybatis
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080
